
name: Bank Frontend Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: skybounds02/main_bank_app_frontend
        ref: main


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Build container image
      run: docker build -t bank-app-frontend:latest .

    - name: Log in to ECR with short-lived credentials
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}
  
    - name: Tag Docker image
      run: docker tag bank-app-frontend:latest ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}
    
    - name: Push image to ECR
      run: docker push ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}


    - name: Clean up Docker image locally
      run: |
        docker rmi bank-app-frontend:latest
        docker rmi ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}

    - name: Clean up GitHub repo on runner
      run: rm -rf ./*


  
  Continues-Update_k8s_manifest:
    runs-on: Linux
    needs: Continues-Integration_build_and_push
    steps:
    - name: Install Git and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        
    - name: Checkout repository.
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/skybounds02/kubernetes-manifest.git
         
         cd kubernetes-manifest
         git config --global user.email "philipsukonu@gmail.com"
         git config --global user.name "Philips2005"

         sed -i "s+${{ vars.ECR_REPO }}/bank-frontend:.*+${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}+g" ./bank-project/frontend.yaml

         cat ./bank-project/frontend.yaml | grep -q "${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}"

         git add bank-project/frontend.yaml
         git commit -m "Update frontend image to version ${{ github.run_number }}"
         git push origin main
